(() => {
  'use strict';
  const C = window.CASE_FILE;
  const app = document.getElementById('app');
  const toast = document.getElementById('toast');
  const state = { screen: 'home', quiz: 0, score: 0, yes: 0, noDodges: 0, noRefused: false, verdicts: 0, audio: false, game: null, gameWon: false };
  let toastTimer;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const goTop = () => window.scrollTo({top:0,behavior:'smooth'});
  function showToast(message) { toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2300); }
  function render() {
    if(state.screen==='home') home();
    else if(state.screen==='quiz') quiz();
    else if(state.screen==='court') court();
    else if(state.screen==='choice') choice();
    else if(state.screen==='game') gameScreen();
    else if(state.screen==='memories') memories();
    else if(state.screen==='final') finalScreen();
    goTop();
  }
  function home(){ app.innerHTML=`<section class="hero" id="home"><div class="hero-copy"><div class="eyebrow">✳ Chuyên án: Giải cứu kỷ niệm 3 năm</div><h1>HỒ SƠ<br>TUYỆT MẬT<br><em>03 NĂM</em></h1><p class="lead"><b>HỒ SƠ TUYỆT MẬT — CHỈ DÀNH CHO ĐẶC VỤ ${esc(C.agentNickname)}</b>. Phòng Hồ sơ Đặc biệt triệu tập bạn điều tra một vụ án rất nghiêm trọng: ${esc(C.caseIntro)}</p><div class="case-facts"><div class="fact"><small>ĐỐI TƯỢNG</small><strong>${esc(C.partnerName)} · ${esc(C.partnerNickname)}</strong></div><div class="fact"><small>NGÀY KHỞI ÁN</small><strong>${esc(C.anniversary)}</strong></div></div><button class="btn btn-primary" id="start">NHẬN NHIỆM VỤ&nbsp; →</button></div><div class="hero-art" aria-label="Bìa hồ sơ mật"><span class="heart-note">♥</span><span class="paperclip">⌁</span><div class="folder"><div class="folder-tag">P.H.S. · ĐƠN VỊ ĐIỀU TRA TÌNH CẢM</div><div class="folder-name">Vụ án: Hai người và chiếc miếng cuối</div><div class="folder-lines">MÃ HỒ SƠ: 03-A<br>ĐỘ MẬT: RẤT ĐÁNG NGỜ<br>TRẠNG THÁI: CÒN THƯƠNG NHAU</div><div class="stamp">TỐI<br>MẬT</div></div></div></section>`;
    document.getElementById('start').onclick=()=>{state.screen='quiz';state.quiz=0;state.score=0;render();};
  }
  function quiz(){let q=C.quiz[state.quiz];if(!q){state.screen='court';return render();}const pct=state.quiz/C.quiz.length*100;app.innerHTML=`<section class="section"><button class="back-link" data-back="home">← Hồ sơ chính</button><div class="section-head"><div><div class="eyebrow">Thẩm vấn đặc vụ</div><h2 class="screen-title">Kiểm tra trí nhớ</h2></div><div class="step-label">HỎI ${state.quiz+1} / ${C.quiz.length}</div></div><div class="card question-card"><div class="progress"><span style="width:${pct}%"></span></div><div class="evidence"><b>🔎</b> TẬP TIN ĐANG MỞ · ${String(state.quiz+1).padStart(2,'0')}</div><h3 class="question">${esc(q.question)}</h3><div class="choices">${q.choices.map((x,i)=>`<button class="choice" data-answer="${i}">${esc(x)}</button>`).join('')}</div><div id="quizFeedback" class="feedback">Chọn phương án mà đặc vụ tin là đúng.</div><div class="action-row"><button class="small-link" id="skipQuiz">Bỏ qua phần hỏi cung</button><button class="btn btn-primary hidden" id="nextQuiz">${state.quiz===C.quiz.length-1?'Ra phiên tòa':'Câu tiếp theo'} →</button></div></div></section>`;
    document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);const right=Number(b.dataset.answer)===q.answer;if(right)state.score++;b.style.borderColor=right?'#638b6f':'#ca5445';document.getElementById('quizFeedback').innerHTML=right?`<b>CHÍNH XÁC!</b> ${esc(q.compliment)}<div class="evidence" style="margin-top:10px"><b>📎</b>${esc(q.evidence)}</div>`:`Không sao, đặc vụ. Hồ sơ ký ức này hơi bụi rồi — vẫn được tiếp tục nhiệm vụ nhé. <div class="evidence" style="margin-top:10px"><b>📎</b>${esc(q.evidence)}</div>`;document.getElementById('nextQuiz').classList.remove('hidden');});
    document.getElementById('nextQuiz').onclick=()=>{state.quiz++;render();};document.getElementById('skipQuiz').onclick=()=>{state.screen='court';render();};bindBack();
  }
  function court(){app.innerHTML=`<section class="section"><button class="back-link" data-back="quiz">← Về thẩm vấn</button><div class="section-head"><div><div class="eyebrow">Tòa án tình yêu · Phiên xử mở</div><h2 class="screen-title">Ai là thủ phạm?</h2><p class="court-intro">Chủ tọa xin nhắc: mọi lời khai đều có thể bị dùng để trêu nhau mãi mãi. Chạm một lần để chọn nghi phạm.</p></div><div class="step-label">PHIÊN 02</div></div><div class="allegations">${C.allegations.map((x,i)=>`<article class="allegation"><span class="count">#${String(i+1).padStart(2,'0')}</span>${esc(x)}<div class="suspects"><button class="verdict-choice" data-charge="${i}" data-party="${esc(C.agentNickname)}">${esc(C.agentNickname)}</button><button class="verdict-choice" data-charge="${i}" data-party="${esc(C.partnerNickname)}">${esc(C.partnerNickname)}</button><button class="verdict-choice" data-charge="${i}" data-party="Cả hai">Cả hai</button></div></article>`).join('')}</div><div id="courtResult" class="court-result">Tòa đang chờ nhân chứng đầu tiên…</div><div class="action-row"><button class="small-link" id="toMemories">Xem kho kỷ niệm ↗</button><button class="btn btn-primary" id="toChoice">Tiếp tục xét xử →</button></div></section>`;
    const lines=['Bị cáo biện hộ bằng nụ cười. Không được chấp nhận làm bằng chứng.','Nhân chứng khai báo rất tự tin — tòa ghi nhận cả hai đều có chút đáng ngờ.','Tòa tuyên: cả hai đều có tội. Hình phạt là tiếp tục thương nhau.','Luật sư xin giảm nhẹ vì bị cáo dễ thương. Tòa đang cân nhắc…'];
    document.querySelectorAll('[data-charge]').forEach(b=>b.onclick=()=>{state.verdicts++;document.querySelectorAll(`[data-charge="${b.dataset.charge}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const party=b.dataset.party;document.getElementById('courtResult').textContent=party==='Cả hai'?lines[2]:`${party} nhận án. ${party===C.agentNickname?'Đặc vụ được phép kháng cáo bằng một cái ôm.':'Tòa miễn giảm vì bị cáo trông có vẻ vô tội.'}`;});
    document.getElementById('toChoice').onclick=()=>{state.screen='choice';render();};document.getElementById('toMemories').onclick=()=>{state.screen='memories';render();};bindBack();
  }
  function choice(){app.innerHTML=`<section class="section"><button class="back-link" data-back="court">← Về phiên tòa</button><div class="section-head"><div><div class="eyebrow">Thử thách cuối · Xác nhận lựa chọn</div><h2 class="screen-title">Đặc vụ có nhận lời?</h2></div><div class="step-label">CẦN PHÊ CHUẨN</div></div><div class="choice-stage"><div class="eyebrow">MỘT CÂU HỎI RẤT QUAN TRỌNG</div><h3>Em có đồng ý tiếp tục đồng hành với anh ở năm thứ tư không?</h3><p>Trả lời thật lòng. Hệ thống có thể hơi thiên vị nút Có.</p><div class="choice-actions" id="choiceActions"><button class="btn btn-primary" id="yesButton">${['Có','Có thật mà','Tin mình đi','Cho mình chứng minh'][Math.min(state.yes,3)]}</button><button class="btn btn-no" id="noButton">${esc(C.noButtonLines[Math.min(state.noDodges,C.noButtonLines.length-1)])}</button></div><div id="choiceStatus" class="choice-status">${state.noDodges>=5?'Thôi, cho bấm được rồi đó. Nhưng mình vẫn hy vọng bạn chọn Có.':''}</div><button id="noContinue" class="btn btn-quiet ${state.noRefused?'':'hidden'}">Mình vẫn muốn tiếp tục nhiệm vụ →</button></div></section>`;
    const no=document.getElementById('noButton'), area=document.getElementById('choiceActions');
    const dodge=ev=>{if(state.noRefused)return;if(state.noDodges<5){ev.preventDefault();ev.stopPropagation();state.noDodges++;no.textContent=C.noButtonLines[Math.min(state.noDodges,C.noButtonLines.length-1)];if(state.noDodges<5){const a=area.getBoundingClientRect(),n=no.getBoundingClientRect(),wantedX=n.left+(Math.random()-.5)*Math.min(120,a.width*.38),wantedY=n.top+(Math.random()-.5)*42,dx=Math.max(a.left,Math.min(a.right-n.width,wantedX))-n.left,dy=Math.max(a.top,Math.min(a.bottom-n.height,wantedY))-n.top;no.style.transform=`translate(${dx}px,${dy}px) rotate(${(Math.random()-.5)*12}deg)`;}else {no.style.transform='';document.getElementById('choiceStatus').textContent='Thôi, cho bấm được rồi đó. Nhưng mình vẫn hy vọng bạn chọn Có.';}return;}state.noRefused=true;document.getElementById('choiceStatus').textContent='Tôn trọng quyết định của đặc vụ. Tòa xin nhắc: vẫn có thể đổi ý bất cứ lúc nào. ♥';document.getElementById('noContinue').classList.remove('hidden');no.textContent='Không, cảm ơn';};
    no.addEventListener('pointerdown',dodge);no.addEventListener('click',ev=>{if(state.noDodges>=5&&!state.noRefused)dodge(ev);else if(state.noRefused){showToast('Được ghi nhận. Chưa đóng hồ sơ đâu nhé.');}});
    document.getElementById('noContinue').onclick=()=>{state.noRefused=false;state.screen='game';render();};
    document.getElementById('yesButton').onclick=()=>{state.yes++;const msgs=['Bốc phét. Trả lời nhanh thế, không có vẻ gì là đã suy nghĩ cả.','Không tin. Ba năm bên nhau mà tưởng bấm Có là qua cửa à?','Được. Chứng minh bằng hành động đi, đặc vụ.'];document.getElementById('choiceStatus').textContent=msgs[Math.min(state.yes-1,2)];if(state.yes>=3){setTimeout(()=>{state.screen='game';render();},700);}};bindBack();
  }
  const game={};
  function gameScreen(){app.innerHTML=`<section class="section"><button class="back-link" data-back="choice">← Về câu hỏi</button><div class="section-head"><div><div class="eyebrow">Thử thách đường trường · Đi hẹn hò</div><h2 class="screen-title">Đua xe kỷ niệm</h2><p class="court-intro">Nhặt 3 kỷ niệm, né chướng ngại và về đích trong 24 giây. Va chạm 3 lần là phải chạy lại.</p></div><div class="step-label">ĐIỂM: <span id="scoreLabel">0 / 3</span></div></div><div class="game-wrap"><div class="game-hud"><b>♥ ♥ ♥ <span id="lifeLabel"></span></b><strong id="timeLabel">24.0s</strong></div><div class="game-frame"><canvas id="race" width="360" height="510" aria-label="Đường đua mini game"></canvas><div id="gameOverlay" class="game-overlay"><div class="game-overlay-inner"><div class="eyebrow">HƯỚNG DẪN ĐẶC VỤ</div><h3>Sẵn sàng xuất phát?</h3><p>Vuốt trái/phải trên đường đua hoặc chạm nút điều khiển. Nhặt ít nhất 3 món kỷ niệm và né các chướng ngại nhé.</p><button class="btn btn-primary" id="startRace">NỔ MÁY →</button></div></div></div><div class="game-controls"><button class="control-btn" id="leftControl" aria-label="Rẽ trái">←</button><div class="control-hint">CHẠM / VUỐT<br>ĐỂ ĐỔI LÀN</div><button class="control-btn" id="rightControl" aria-label="Rẽ phải">→</button></div></div></section>`;
    bindBack();setupRace();
  }
  function setupRace(){const canvas=document.getElementById('race'),ctx=canvas.getContext('2d'),W=360,H=510;const g={lane:1,items:[],score:0,lives:3,time:24,elapsed:0,last:0,spawn:0,running:false,ended:false,raf:0,hitFlash:0};state.game=g;
    const lanes=[85,180,275];function laneMove(d){if(g.running)g.lane=Math.max(0,Math.min(2,g.lane+d));}
    const left=document.getElementById('leftControl'),right=document.getElementById('rightControl');left.onpointerdown=e=>{e.preventDefault();laneMove(-1)};right.onpointerdown=e=>{e.preventDefault();laneMove(1)};
    let touchX=0;canvas.onpointerdown=e=>{if(!g.running)return;touchX=e.clientX;canvas.setPointerCapture?.(e.pointerId);};canvas.onpointerup=e=>{if(!g.running)return;const dx=e.clientX-touchX;if(Math.abs(dx)>18)laneMove(dx<0?-1:1);else{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left;laneMove(x<r.width/2?-1:1);}};
    const key=e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'){e.preventDefault();laneMove(-1)}if(e.key==='ArrowRight'||e.key.toLowerCase()==='d'){e.preventDefault();laneMove(1)}};window.addEventListener('keydown',key,{once:true});
    function draw(now){if(state.screen!=='game')return;const dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(W*dpr)||canvas.height!==Math.round(H*dpr)){canvas.width=W*dpr;canvas.height=H*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);
      ctx.fillStyle='#536653';ctx.fillRect(0,0,W,H);ctx.fillStyle='#26342e';ctx.fillRect(35,0,290,H);ctx.fillStyle='#34453c';ctx.fillRect(43,0,274,H);
      const offset=(g.elapsed*115)%70;ctx.strokeStyle='#cbbd8b';ctx.lineWidth=3;ctx.setLineDash([23,19]);ctx.lineDashOffset=-offset;ctx.beginPath();ctx.moveTo(132,0);ctx.lineTo(132,H);ctx.moveTo(228,0);ctx.lineTo(228,H);ctx.stroke();ctx.setLineDash([]);
      // soft roadside markers
      for(let y=-20+offset;y<H;y+=70){ctx.fillStyle='#d7c49b';ctx.fillRect(17,y,10,25);ctx.fillRect(333,y+30,10,25);}
      if(g.running){const dt=Math.min(.05,(now-g.last)/1000||0);g.elapsed+=dt;g.time=Math.max(0,24-g.elapsed);g.spawn-=dt;g.hitFlash=Math.max(0,g.hitFlash-dt);if(g.spawn<=0){const collect=Math.random()<.62;g.items.push({lane:Math.floor(Math.random()*3),y:-30,kind:collect?'item':'obstacle',symbol:collect?C.gameItems[Math.floor(Math.random()*C.gameItems.length)]:C.gameObstacles[Math.floor(Math.random()*C.gameObstacles.length)],done:false});g.spawn=.8+Math.random()*.36;}g.items.forEach(o=>{o.y+=dt*156;if(o.y>414&&o.y<470&&!o.done&&o.lane===g.lane){o.done=true;if(o.kind==='item')g.score++;else {g.lives--;g.hitFlash=.35;}}});g.items=g.items.filter(o=>o.y<H+35);document.getElementById('scoreLabel').textContent=`${g.score} / 3`;document.getElementById('lifeLabel').textContent='♥ '.repeat(Math.max(0,g.lives));document.getElementById('timeLabel').textContent=`${g.time.toFixed(1)}s`;if(g.lives<=0)endRace(false);else if(g.time<=0)endRace(g.score>=3);}
      g.items.forEach(o=>{ctx.font='27px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.symbol,lanes[o.lane],o.y);});
      // player's car
      const px=lanes[g.lane],py=437;ctx.fillStyle=g.hitFlash>0?'#ff8f7e':'#ed7160';ctx.beginPath();ctx.roundRect(px-19,py-29,38,58,11);ctx.fill();ctx.fillStyle='#ffe9bc';ctx.beginPath();ctx.roundRect(px-13,py-20,26,18,6);ctx.fill();ctx.fillStyle='#303840';ctx.fillRect(px-22,py-17,5,13);ctx.fillRect(px+17,py-17,5,13);ctx.fillRect(px-22,py+12,5,13);ctx.fillRect(px+17,py+12,5,13);ctx.fillStyle='#8e3340';ctx.fillRect(px-10,py+7,20,3);
      g.last=now;if(g.running)g.raf=requestAnimationFrame(draw);
    }
    function begin(){g.running=true;g.last=performance.now();document.getElementById('gameOverlay').classList.add('hidden');g.raf=requestAnimationFrame(draw);}
    function endRace(win){if(g.ended)return;g.running=false;g.ended=true;cancelAnimationFrame(g.raf);const overlay=document.getElementById('gameOverlay');overlay.classList.remove('hidden');overlay.innerHTML=`<div class="game-overlay-inner"><div class="eyebrow">${win?'BẰNG CHỨNG ĐÃ ĐƯỢC XÁC NHẬN':'XE TUẦN TRA TẠM DỪNG'}</div><h3>${win?'Đã về đích!':'Chưa tới đích rồi!'}</h3><p>${win?'Đã chứng minh được là vẫn chịu đồng hành. Nhặt được '+g.score+' kỷ niệm! Nút Có thật đã mở khóa.':'Xe có thể lật, nhưng tình yêu không được phép bỏ cuộc. Có '+g.score+' kỷ niệm — chạy lại nhé?'}</p>${win?'<button class="btn btn-primary" id="unlockYes">CÓ — MỞ KẾT LUẬN ♥</button>':'<button class="btn btn-primary" id="retryRace">CHẠY LẠI →</button>'}</div>`;if(win){state.gameWon=true;confetti();document.getElementById('unlockYes').onclick=()=>{state.screen='final';render();confetti();};}else document.getElementById('retryRace').onclick=()=>{gameScreen();};}
    function initial(){draw(0);document.getElementById('startRace').onclick=begin;}initial();
  }
  function memories(){app.innerHTML=`<section class="section"><button class="back-link" data-back="court">← Quay lại hành trình</button><div class="section-head"><div><div class="eyebrow">Kho chứng cứ đã mở</div><h2 class="screen-title">Bản đồ ba năm</h2><p class="court-intro">Một vài trang hồ sơ vẫn chờ hai nhân chứng bổ sung ký ức thật.</p></div><div class="step-label">MỤC LỤC · 05</div></div><div class="timeline">${C.milestones.map(m=>`<article class="memory"><div class="memory-side"><div class="memory-date">${esc(m.date)}</div><h3>${esc(m.title)}</h3><p>${esc(m.text)}</p></div>${m.image?`<img src="${esc(m.image)}" alt="${esc(m.title)}" onerror="this.outerHTML='<div class=memory-placeholder>ẢNH CHƯA THÊM · CẬP NHẬT TRONG CONFIG.JS</div>'">`:'<div class="memory-placeholder">ẢNH / KỶ VẬT CÓ THỂ THÊM TẠI CONFIG.JS</div>'}</article>`).join('')}</div><div class="action-row"><button class="small-link" id="backToChoice">Quay lại nhiệm vụ</button><button class="btn btn-primary" id="finishCase">${state.gameWon?'Mở kết luận hồ sơ →':'Quay lại nhiệm vụ →'}</button></div></section>`;document.getElementById('finishCase').onclick=()=>{if(!state.gameWon){state.screen='choice';render();return;}state.screen='final';render();confetti();};document.getElementById('backToChoice').onclick=()=>{state.screen='choice';render();};bindBack();}
  function finalScreen(){if(!state.gameWon){state.screen='game';return gameScreen();}app.innerHTML=`<section class="section"><button class="back-link" id="reviewJourney">← Xem lại hành trình</button><div class="card final-card"><div class="final-seal">NHIỆM VỤ<br>HOÀN TẤT</div><div class="eyebrow">PHÒNG HỒ SƠ ĐẶC BIỆT · KHÉP HỒ SƠ 03-A</div><h2 class="screen-title">Ba năm. Một đội.<br><span style="color:var(--red)">Rất nhiều thương.</span></h2>${C.sharedPhoto?`<img src="${esc(C.sharedPhoto)}" alt="Ảnh của hai người" style="width:100%;max-height:360px;object-fit:cover;border-radius:8px;margin-top:15px" onerror="this.style.display='none'">`:''}<p class="final-message">${esc(C.finalMessage)}</p><div class="date-invite"><h3>Thư mời hẹn hò chính thức 💌</h3><div class="invite-grid"><div class="invite-item"><small>THỜI GIAN</small><b>${esc(C.dateNight.when)}</b></div><div class="invite-item"><small>ĐỊA ĐIỂM</small><b>${esc(C.dateNight.where)}</b></div><div class="invite-item"><small>TRANG PHỤC</small><b>${esc(C.dateNight.dress)}</b></div><div class="invite-item"><small>KẾ HOẠCH</small><b>${esc(C.dateNight.plan)}</b></div></div></div><div class="media-controls">${C.songUrl?`<a href="${esc(C.songUrl)}" target="_blank" rel="noopener">♫ Bài hát của chúng mình</a>`:''}${C.voiceUrl?`<audio controls preload="none" src="${esc(C.voiceUrl)}">Trình duyệt không hỗ trợ âm thanh.</audio>`:''}<button id="reviewMemories">Mở lại kho kỷ niệm ↗</button><button id="restart">Chơi lại từ đầu ↺</button></div></div></section>`;document.getElementById('reviewJourney').onclick=()=>{state.screen='memories';render();};document.getElementById('reviewMemories').onclick=()=>{state.screen='memories';render();};document.getElementById('restart').onclick=()=>{Object.assign(state,{screen:'home',quiz:0,score:0,yes:0,noDodges:0,noRefused:false,verdicts:0,gameWon:false});render();};}
  function bindBack(){document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.back;render();});}
  function confetti(){const icons=['♥','✦','✿','♥','★'];for(let i=0;i<22;i++){const el=document.createElement('span');el.className='confetti';el.textContent=icons[Math.floor(Math.random()*icons.length)];el.style.left=Math.random()*100+'vw';el.style.top=(48+Math.random()*32)+'vh';el.style.color=['#ca5445','#d9a94f','#638b6f'][i%3];el.style.setProperty('--dx',(Math.random()-.5)*180+'px');document.body.appendChild(el);setTimeout(()=>el.remove(),1600);}}
  document.getElementById('soundToggle').onclick=e=>{state.audio=!state.audio;e.currentTarget.innerHTML=`♪ <span>Âm thanh: ${state.audio?'bật':'tắt'}</span>`;if(state.audio)showToast('Đã bật tiếng xác nhận thao tác.');};
  document.addEventListener('click',e=>{if(!state.audio||!e.target.closest('button')||e.target.closest('#soundToggle'))return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;const ac=new Audio(),osc=ac.createOscillator(),gain=ac.createGain();osc.type='sine';osc.frequency.value=740;gain.gain.setValueAtTime(.035,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.09);osc.connect(gain);gain.connect(ac.destination);osc.start();osc.stop(ac.currentTime+.09);osc.onended=()=>ac.close();}catch(_){/* Audio is optional; interaction remains fully available. */}});
  document.getElementById('replayLink').onclick=()=>{if(state.screen==='home')showToast('Đặc vụ đang ở trang đầu hồ sơ.');else if(state.screen==='final'){state.screen='memories';render();}else{state.screen='home';render();}};
  render();
})();
